const WHATSAPP_NUMBER = "5492213541722";

let CORTES = [
  {
    id: "vacio",
    nombre: "Vacío",
    categoria: "clasicos",
    desc: "Corte tierno y jugoso, ideal para la parrilla. Con su característica capa de grasa que le da un sabor inigualable.",
    meta: { coccion: "Parrilla", punto: "Jugoso (a punto)", tiempo: "15-20 min" },
  },
  {
    id: "tapa-asado",
    nombre: "Tapa de Asado",
    categoria: "clasicos",
    desc: "La tapa del asado de tira, con esa grasa que al derretirse sobre las brasas da un sabor único.",
    meta: { coccion: "Parrilla lenta", punto: "Bien cocido", tiempo: "40-60 min" },
  },
  {
    id: "matambre",
    nombre: "Matambre",
    categoria: "clasicos",
    desc: "Corte fino y versátil. Ideal arrollado o a la parrilla. Relleno de verduras y huevo es un clásico.",
    meta: { coccion: "Parrilla", punto: "Cocido completo", tiempo: "25-35 min" },
  },
  {
    id: "entrana",
    nombre: "Entraña",
    categoria: "clasicos",
    desc: "Corte delgado y muy sabroso. Se cocina rápido y queda crocante por fuera, jugosa por dentro. Imperdible.",
    meta: { coccion: "Parrilla muy caliente", punto: "Jugosa", tiempo: "6-10 min" },
  },
  {
    id: "lomo",
    nombre: "Lomo",
    categoria: "clasicos",
    desc: "El corte más tierno. Magro y suave, perfecto para horno o plancha. Ideal para ocasiones especiales.",
    meta: { coccion: "Horno o plancha", punto: "Jugoso (a punto)", tiempo: "20-30 min" },
  },
  {
    id: "peceto",
    nombre: "Peceto",
    categoria: "clasicos",
    desc: "Corte magro y tierno, ideal para roast beef, milanesas o al horno con verduras.",
    meta: { coccion: "Horno", punto: "A punto", tiempo: "50-60 min" },
  },
  {
    id: "nalga",
    nombre: "Nalga",
    categoria: "clasicos",
    desc: "Magro y versátil, perfecto para milanesas, bocados o a la plancha.",
    meta: { coccion: "Plancha o sartén", punto: "A punto", tiempo: "8-12 min" },
  },
  {
    id: "bola-lomo",
    nombre: "Bola de Lomo",
    categoria: "clasicos",
    desc: "Tierno y magro, ideal para porciones al horno o brochettes.",
    meta: { coccion: "Horno", punto: "Jugoso (a punto)", tiempo: "35-45 min" },
  },
  {
    id: "cuadrada",
    nombre: "Cuadrada",
    categoria: "clasicos",
    desc: "Ideal para roast beef o cocción al horno. Rinde y no falla.",
    meta: { coccion: "Horno", punto: "A punto", tiempo: "60-70 min" },
  },
  {
    id: "cuadril",
    nombre: "Cuadril",
    categoria: "clasicos",
    desc: "Sabor intenso y textura firme. Excelente a la parrilla o al horno.",
    meta: { coccion: "Parrilla", punto: "Jugoso (a punto)", tiempo: "20-25 min" },
  },
  {
    id: "colita-cuadril",
    nombre: "Colita de Cuadril",
    categoria: "clasicos",
    desc: "El corte de los asados especiales. Tierno, jugoso y con sabor inigualable a la parrilla.",
    meta: { coccion: "Parrilla", punto: "Jugoso (a punto)", tiempo: "25-30 min" },
  },
  {
    id: "bifes",
    nombre: "Bifes",
    categoria: "clasicos",
    desc: "Listos para la plancha o la parrilla. Prácticos y rendidores.",
    meta: { coccion: "Plancha o sartén", punto: "A punto", tiempo: "6-8 min" },
  },
  {
    id: "roast-beef",
    nombre: "Roast Beef",
    categoria: "clasicos",
    desc: "El clásico de mesa. Ideal al horno, caliente o frío, para toda ocasión.",
    meta: { coccion: "Horno", punto: "A punto", tiempo: "60-75 min" },
  },
  {
    id: "paleta",
    nombre: "Paleta",
    categoria: "clasicos",
    desc: "Versátil y económica. Ideal al horno, estofada o a la parrilla.",
    meta: { coccion: "Horno o estofado", punto: "Bien cocido", tiempo: "90-120 min" },
  },
  {
    id: "picada",
    nombre: "Picada",
    categoria: "clasicos",
    desc: "Cortes chicos listos para la picada o para saltear. Rinde y gusta.",
    meta: { coccion: "Sartén", punto: "Cocido", tiempo: "5-8 min" },
  },
  {
    id: "osobuco",
    nombre: "Osobuco",
    categoria: "clasicos",
    desc: "Corte con hueso y médula. Ideal para guisos y estofados de cocción lenta.",
    meta: { coccion: "Estofado", punto: "Muy tierno", tiempo: "120-150 min" },
  },
  {
    id: "t-bone",
    nombre: "T-Bone",
    categoria: "premium",
    desc: "Dos cortes en uno: lomo y bife separados por su hueso en T. La experiencia premium de la parrilla.",
    meta: { coccion: "Parrilla alta", punto: "Jugoso (a punto)", tiempo: "15-20 min" },
  },
  {
    id: "tomahawk",
    nombre: "Tomahawk",
    categoria: "premium",
    desc: "El corte más imponente. Bife de chorizo con hueso largo, ideal para reverse sear y sorprender a todos.",
    meta: { coccion: "Reverse sear", punto: "Jugoso (a punto)", tiempo: "30-40 min" },
  },
  {
    id: "picana",
    nombre: "Picaña (Tapa de Cuadril)",
    categoria: "premium",
    desc: "La tapa de cuadril con su capa de grasa que la hace jugosa, de sabor intenso e inconfundible.",
    meta: { coccion: "Parrilla", punto: "Jugosa", tiempo: "20-25 min" },
  },
  {
    id: "ojo-bife",
    nombre: "Ojo de Bife",
    categoria: "premium",
    desc: "El ribeye argentino. Marmoleado generoso y sabor profundo, rey de la parrilla premium.",
    meta: { coccion: "Parrilla alta", punto: "Jugoso (a punto)", tiempo: "15-20 min" },
  },
  {
    id: "pecho",
    nombre: "Pecho",
    categoria: "premium",
    desc: "Con marmoleado natural, ideal para cocciones lentas que se deshacen en la boca.",
    meta: { coccion: "Cocción lenta", punto: "Muy tierno", tiempo: "180-240 min" },
  },
  {
    id: "bife-chorizo",
    nombre: "Bife de Chorizo",
    categoria: "premium",
    desc: "El corte estrella de la parrilla argentina. Firme, jugoso y con el sabor justo para no fallar nunca.",
    meta: { coccion: "Parrilla o plancha", punto: "Jugoso (a punto)", tiempo: "12-18 min" },
  },
  {
    id: "asado",
    nombre: "Asado de Tira",
    categoria: "clasicos",
    desc: "El corte nacional. Tira de asado con hueso y grasita que se derrite sobre las brasas.",
    meta: { coccion: "Parrilla", punto: "A punto, bien jugoso", tiempo: "50-70 min" },
  },
  {
    id: "falda",
    nombre: "Falda",
    categoria: "clasicos",
    desc: "Corte con tira de grasa y sabor intenso. Ideal para cocciones lentas y guisos que se deshacen.",
    meta: { coccion: "Cocción lenta", punto: "Muy tierno", tiempo: "90-120 min" },
  },
];

let COMBOS = [
  {
    id: "combo-asado",
    icon: "🔥",
    nombre: "Combo Asado para 4",
    detalle: "2kg de tapa de asado + 1kg de vacío + 1kg de entraña",
  },
  {
    id: "combo-parrillada",
    icon: "🥩",
    nombre: "Combo Parrillada para 6",
    detalle: "2kg de tapa de asado + 2kg de vacío + 1kg de matambre + 1kg de entraña",
  },
  {
    id: "combo-premium",
    icon: "⭐",
    nombre: "Combo Premium para 2",
    detalle: "1kg de lomo + 1kg de picaña (tapa de cuadril)",
  },
];
